name: Dokka GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04

    env:
      GRADLE_ARGS: >-
        --no-daemon
        --max-workers 2
        -Pkotlin.incremental=false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-dokka/htmlMultiModule-${{ hashFiles('**/build.gradle.kt') }}
          restore-keys: |
            ${{ runner.os }}-dokka/htmlMultiModule-
            ${{ runner.os }}-
      - name: Dokka
        run: ./gradlew $GRADLE_ARGS dokkaHtmlMultiModule

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          BRANCH: gh-pages
          FOLDER: build/dokka/htmlMultiModule
